In [3]:
import torch

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points, points.shape

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
 torch.Size([3, 2]))

In [4]:
img_t = torch.randn(3, 5, 5)


batch_t = torch.randn(2, 3, 5, 5)
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [5]:
weights = torch.tensor([0.33, 0.33, 0.33])
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

### Named Tensor

In [6]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

D:\home\slime3251\AppData\Local\Temp\ipykernel_4968\2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\c10/core/TensorImpl.h:1408.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [7]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [8]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [9]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [10]:
points_64 = torch.rand(5, dtype=torch.double)
points_64

tensor([0.2653, 0.7885, 0.3261, 0.7551, 0.7180], dtype=torch.float64)

### Tensor API

In [11]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [12]:
a = torch.arange(6)

a.storage()

 0
 1
 2
 3
 4
 5
[torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [14]:
b = a.view(2,3)
b,  b.storage()

(tensor([[0, 1, 2],
         [3, 4, 5]]),
  0
  1
  2
  3
  4
  5
 [torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 6])

In [16]:
c = a[3:]
c, c.storage(), id(a.storage()) == id(b.storage())  == id(c.storage())

(tensor([3, 4, 5]),
  0
  1
  2
  3
  4
  5
 [torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 6],
 True)

In [17]:
b, b.stride(), b.stride(0), b.stride(1)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 (3, 1),
 3,
 1)

In [18]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)

some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [19]:
some_t.stride(), transpose_t.stride()

((20, 5, 1), (1, 5, 20))