In [1]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.8746,  0.5724,  2.5310], requires_grad=True)


In [2]:
y = x + 2 
print(y)

tensor([1.1254, 2.5724, 4.5310], grad_fn=<AddBackward0>)


In [4]:
z = y ** 2 * 2
z = z.mean()

print(z)

tensor(18.9421, grad_fn=<MeanBackward0>)


In [5]:
z.backward() # dz/dx
print(x.grad)

tensor([1.5005, 3.4298, 6.0413])
