In [2]:
import os
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred
    
model = Model(n_input_features=6)

if not os.path.exists("models"):
    os.makedirs("models")

FILE = "models/model.pth"
torch.save(model, FILE)

In [3]:
model = torch.load(FILE)
model.eval()

for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.3770, -0.1158,  0.0399, -0.1321,  0.2163,  0.2126]],
       requires_grad=True)
Parameter containing:
tensor([-0.1888], requires_grad=True)


### Recommand

In [5]:
FILE = "models/model.pth"
torch.save(model.state_dict(), FILE)

loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

for param in loaded_model.parameters():
    print(param)

Parameter containing:
tensor([[-0.3770, -0.1158,  0.0399, -0.1321,  0.2163,  0.2126]],
       requires_grad=True)
Parameter containing:
tensor([-0.1888], requires_grad=True)
